# Generated by Django 5.0.3 on 2024-05-07 16:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='deleted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='deleted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
