# Generated by Django 5.0.3 on 2024-04-17 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_amount_alter_product_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_public',
        ),
    ]
