# Generated by Django 5.0.3 on 2024-05-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='boughtCount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='reviewCount',
            field=models.FloatField(default=0),
        ),
    ]
