# Generated by Django 5.0.3 on 2024-05-16 02:32

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_boughtcount_product_reviewcount'),
    ]
    
                        
    operations = [
       
    ]