# Generated by Django 5.0.3 on 2024-05-16 07:44

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20240516_0932'),
    ]
    
    operations = [
    ]
