# Generated by Django 5.0.3 on 2024-05-16 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20240516_1456'),
    ]
    operations = [
    ]
