# Generated by Django 5.0.3 on 2024-05-16 08:47

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20240516_1527'),
    ]
    
    operations = [
    ]