# Generated by Django 5.0.3 on 2024-05-16 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20240516_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='boughtCount',
            new_name='bought_count',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='reviewCount',
            new_name='review_count',
        ),
    ]
